# @spec[PARKOUR.md#Requirements]
"""PARKOUR virtual-model planning and execution primitives."""

from .planning import (
    ExecutionPlan,
    GraphAnalysis,
    PlanLimits,
    PlanValidationError,
    SubtaskSpec,
    analyze_plan,
    build_direct_plan,
    parse_execution_plan,
    should_decompose,
)
from .scheduler import (
    DagScheduler,
    DependencyContext,
    NodeResult,
    ParkourLimitError,
    SchedulerLimits,
    SchedulerResult,
    UpstreamBudget,
    WorkerResult,
    routed_gateway_worker,
)
from .engine import EngineResult, ParkourEngine, ParkourExecutionError
from .research import (
    Citation,
    HttpSearchProvider,
    ResearchBlockedError,
    ResearchError,
    ResearchLimitError,
    ResearchLimits,
    ResearchResult,
    ResearchSession,
    ResearchTelemetry,
    RawResult,
    build_research_session,
    domain_allowed,
    guard_url,
    mask_secret,
    research_telemetry,
)
from .refinement import (
    RefinementError,
    RefinementLimits,
    RefinementResult,
    RefinementTelemetry,
    ReviseOutcome,
    Verdict,
    VerifyOutcome,
    parse_verdict,
    refinement_telemetry,
    run_refinement,
)
from .ensemble import (
    EnsembleError,
    EnsembleTelemetry,
    MemberResult,
    PanelResult,
    ensemble_telemetry,
    run_panel,
)

__all__ = [
    "ExecutionPlan",
    "GraphAnalysis",
    "PlanLimits",
    "PlanValidationError",
    "SubtaskSpec",
    "analyze_plan",
    "build_direct_plan",
    "parse_execution_plan",
    "should_decompose",
    "DagScheduler",
    "DependencyContext",
    "NodeResult",
    "ParkourLimitError",
    "SchedulerLimits",
    "SchedulerResult",
    "UpstreamBudget",
    "WorkerResult",
    "routed_gateway_worker",
    "EngineResult",
    "ParkourEngine",
    "ParkourExecutionError",
    "Citation",
    "HttpSearchProvider",
    "ResearchBlockedError",
    "ResearchError",
    "ResearchLimitError",
    "ResearchLimits",
    "ResearchResult",
    "ResearchSession",
    "ResearchTelemetry",
    "RawResult",
    "build_research_session",
    "domain_allowed",
    "guard_url",
    "mask_secret",
    "research_telemetry",
    "RefinementError",
    "RefinementLimits",
    "RefinementResult",
    "RefinementTelemetry",
    "ReviseOutcome",
    "Verdict",
    "VerifyOutcome",
    "parse_verdict",
    "refinement_telemetry",
    "run_refinement",
    "EnsembleError",
    "EnsembleTelemetry",
    "MemberResult",
    "PanelResult",
    "ensemble_telemetry",
    "run_panel",
]
